In [2]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [3]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()
# df.duplicated()
# df.dtypes
#df.tail()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
#filling the null value with the median rating of ech category
df['Review Rating'] = (
    df.groupby('Category')['Review Rating']
      .transform(lambda x: x.fillna(x.median()))
)

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns=df.columns.str.lower()

df.columns=df.columns.str.replace(' ','_')

df=df.rename(columns={'purchase_amount_(usd)':"purchase_amount"})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [9]:
#creating a new cols age_group
#q-cut devide the age into 4 labels
labels=['Young Adult', 'Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [10]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [11]:
# create a column purchase_frequency_days
frequency_mapping={
  'Fortnightly':14,
  'Weekly':7,
  'Monthly':30,
  'Quarterly':90,
  'Bi-Weekly':14,
  "Annually":365,
  'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [12]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [13]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [14]:
# so we remove the one column
df=df.drop('promo_code_used',axis=1)

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [16]:
#>>>connecting sql server through here 

#pip install pandas jupyter sqlalchemy pyodbc ipykernel

# pandas	Data analysis/DataFrames
# jupyter	Jupyter Notebook
# sqlalchemy	Database connection
# pyodbc	Connect Python to SQL Server
# ipykernel	Make your virtual environment available in Jupyter

In [17]:
import sys
print(sys.executable)

C:\Users\sidpa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe

In [18]:
%pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\sidpa\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\sidpa\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\sidpa\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sidpa\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\sidpa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [19]:
import pyodbc
import sqlalchemy

from sqlalchemy import create_engine
from urllib.parse import quote_plus

print("Pandas:", pd.__version__)
print("PyODBC:", pyodbc.version)
print("SQLAlchemy:", sqlalchemy.__version__)

Pandas: 3.0.5
PyODBC: 5.3.0
SQLAlchemy: 2.0.52

In [20]:
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [ ]:
server="SID369"
database="customer_relationship"

connection_string=(
  f"Driver={{ODBC Driver 17 for SQL Server}};"
  f"SERVER={server};"
  f"DATABASE={database};"
  f"TRUSTED_Connection=yes;"
  f"TrustServerCertificate=yes;"
  
)

engine=create_engine("mssql+pyodbc:///?odbc_connect=" + quote_plus(connection_string)
)
print("connection steblished!!")

connection steblished!!

In [22]:
with engine.connect() as conn:
   print("Connected successfully!")

Connected successfully!

In [23]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [24]:
#2load dataframe into sql server
table_name="customer" #chooses any table name
df.to_sql(table_name,engine,if_exists="replace",index=False)

print(f"Data Sucessfully loaded into table{table_name}in database :{database}")

Data Sucessfully loaded into tablecustomerin database :customer_relationship

In [26]:
df.head

<bound method NDFrame.head of       customer_id  age  gender item_purchased     category  purchase_amount  \
0               1   55    Male         Blouse     Clothing               53
1               2   19    Male        Sweater     Clothing               64
2               3   50    Male          Jeans     Clothing               73
3               4   21    Male        Sandals     Footwear               90
4               5   45    Male         Blouse     Clothing               49
...           ...  ...     ...            ...          ...              ...
3895         3896   40  Female         Hoodie     Clothing               28
3896         3897   52  Female       Backpack  Accessories               49
3897         3898   46  Female           Belt  Accessories               33
3898         3899   44  Female          Shoes     Footwear               77
3899         3900   52  Female        Handbag  Accessories               81

           location size      color  season  review_rating  \
0          Kentucky    L       Gray  Winter            3.1
1             Maine    L     Maroon  Winter            3.1
2     Massachusetts    S     Maroon  Spring            3.1
3      Rhode Island    M     Maroon  Spring            3.5
4            Oregon    M  Turquoise  Spring            2.7
...             ...  ...        ...     ...            ...
3895       Virginia    L  Turquoise  Summer            4.2
3896           Iowa    L      White  Spring            4.5
3897     New Jersey    L      Green  Spring            2.9
3898      Minnesota    S      Brown  Summer            3.8
3899     California    M      Beige  Spring            3.1

     subscription_status   shipping_type discount_applied  previous_purchases  \
0                    Yes         Express              Yes                  14
1                    Yes         Express              Yes                   2
2                    Yes   Free Shipping              Yes                  23
3                    Yes    Next Day Air              Yes                  49
4                    Yes   Free Shipping              Yes                  31
...                  ...             ...              ...                 ...
3895                  No  2-Day Shipping               No                  32
3896                  No    Store Pickup               No                  41
3897                  No        Standard               No                  24
3898                  No         Express               No                  24
3899                  No    Store Pickup               No                  33

     payment_method frequency_of_purchases    age_group  \
0             Venmo            Fortnightly  Middle-aged
1              Cash            Fortnightly  Young Adult
2       Credit Card                 Weekly  Middle-aged
3            PayPal                 Weekly  Young Adult
4            PayPal               Annually  Middle-aged
...             ...                    ...          ...
3895          Venmo                 Weekly        Adult
3896  Bank Transfer              Bi-Weekly  Middle-aged
3897          Venmo              Quarterly  Middle-aged
3898          Venmo                 Weekly        Adult
3899          Venmo              Quarterly  Middle-aged

      purchase_frequency_days
0                          14
1                          14
2                           7
3                           7
4                         365
...                       ...
3895                        7
3896                       14
3897                       90
3898                        7
3899                       90

[3900 rows x 19 columns]>

In [28]:
df.tail(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
3890,3891,35,Female,Shirt,Clothing,81,Nebraska,XL,Green,Winter,2.6,No,Standard,No,33,Debit Card,Annually,Adult,365
3891,3892,36,Female,Dress,Clothing,30,Colorado,L,Peach,Winter,4.7,No,Free Shipping,No,6,Bank Transfer,Quarterly,Adult,90
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,L,Indigo,Summer,3.5,No,Standard,No,5,PayPal,Fortnightly,Adult,14
3893,3894,21,Female,Hat,Accessories,64,Massachusetts,L,White,Fall,3.3,No,Store Pickup,No,29,Bank Transfer,Bi-Weekly,Young Adult,14
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,L,White,Spring,3.9,No,2-Day Shipping,No,44,Credit Card,Every 3 Months,Senior,90
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-aged,90